### ISSUE TITLE
ESP-12 breakout has 8 pins

### ISSUE THREAD

**Issue by Geving** [nkolban/fritzing#1]
The PCB version of the ESP-12 breakout has way too few pins.

**Comment by nkolban** [comment]
Do you have a link to a screen shot with the correct number of pins?

**Comment by Geving** [comment]
No, if I had, I would have uploaded the corrected file.
As it is right now, the PCB only has 8 pins, but the breadboard has 16.

This preview from the Fritzing Inspector shows the two side-by-side
![image](https://cloud.githubusercontent.com/assets/3813339/11914325/c90c5966-a67d-11e5-9ee1-f6f71408befb.png)

**Comment by kfowlks** [comment]
I noticed the same issue. It looks like the svg for this part is using the incorrect SVG for the PCB layout. 
![screenshot from 2016-01-09 13-31-11](https://cloud.githubusercontent.com/assets/1541807/12217658/5e04af66-b6d5-11e5-8826-ba1fb44acad6.png)

**Comment by kfowlks** [comment]
I've corrected the issue and created a pull request.
